# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: '&6RegionRegen &8>> '
debug-enabled: false

events:
  break:
    enabled: true
    deny-drops: true
    default-delay: 10
    excluded-blocks:
      - FIRE
    obstruct-prevention:
      enabled: true
      radius: 1
  place:
    enabled: true
    decay-time: 30
    deny-drops: true
    assign-to-decay: true
  explosion:
    enabled: false
    deny-drops: false
  physics:
    enabled: true

messages:
  reloaded: '&7Reloaded.'
  invalid-world: '&cWorld &f%param% &cis invalid.'
  reset-done: '&7Reset &f%count% &7regeneration tasks.'
  reset-done-world: '&7Reset &f%count% &7regeneration tasks in world &f%world%'
